[ADD] Added access rights and rules of proposal model for Portal group
AwesomeFoodCoops/odoo-production pull request #1021
Opened 2020-03-11 11:29 UTC by krunal267

Task URL:

https://www.druidoo.io/web#id=1844&model=project.task&view_type=form&menu_id=237

2020-03-11 14:00 UTC, ivantodorovich requested changes
Regarding the use of sudo().

I'm answring your comment here:

> I have added access rights and rules of proposal model for Portal group as proposal record's state field is getting changed while cancelling it, so if we use sudo() then it would become difficult to track who changed the record.

Not sure I understand, which fields would we be losing?
Is it only the create_uid/write_uid, or are you worried about some others?

We can use sudo() and then write on the fields you're worried about, if tht's an issue.


---

Anyways, any approach is ok to me. But if we go for security rules please make sure everything works as expected. ^^

2020-03-11 14:00 UTC, ivantodorovich commented on intercoop_addons/coop_memberspace/security/ir_rule.xml
> +
Don't we need a [(1,'=',1)] rule for manager user groups?

I'm not familiar with this module but I don't want to break it while trying to fix it ^^

2020-03-26 14:46 UTC, ivantodorovich commented on intercoop_addons/coop_memberspace/security/ir_rule.xml
> +
@krunal267 No hurry but please revert on this pls so we can close it :)

2020-03-30 08:21 UTC, msdruidoo commented
@krunal267 
could you update on this one please?

2020-04-10 09:05 UTC, closed without merging