[ADD] DIAPAR Improvements:Create products
AwesomeFoodCoops/odoo-production pull request #1034
Opened 2020-04-22 09:21 UTC by siddharth7815

Taks Link:

https://www.druidoo.io/web?db=druidoo-druidoo-master-349765&token=J39sYB1yfc1NMuVYgIBr#id=2169&action=367&model=project.task&view_type=form&menu_id=237

2020-04-22 10:39 UTC, ivantodorovich requested changes
Minor comments on code-style, but looks great
Thanks!

2020-04-22 10:39 UTC, ivantodorovich commented on louve_addons/edi_purchase_base/models/supplier_price_list.py
> +                                                               })
```suggestion
        product_tmpl_id = self.env['product.template'].create({
            'name': self.product_name,
            'sale_ok': True,
            'purchase_ok': True,
            'type': 'product',
        })
```

In the future please use this code-style

2020-04-22 10:39 UTC, ivantodorovich commented on louve_addons/edi_purchase_base/models/supplier_price_list.py
> +                                               ('product_tmpl_id', '=', False)])
```suggestion
        supplier_price_list_ids = self.search([
            ('supplier_id', '=', self.supplier_id.id),
            ('product_name', '=', self.product_name),
            ('supplier_code', '=', self.supplier_code),
            ('product_tmpl_id', '=', False),
        ])
```

same here.

It results in more readable code and fewer changed lines in future commits

2020-04-22 10:39 UTC, ivantodorovich commented on louve_addons/edi_purchase_base/models/supplier_price_list.py
> +
```suggestion
```
Also avoid adding meaningless empty lines.
Comments are great, meaningless empty lines are not

2020-04-22 10:39 UTC, ivantodorovich commented on louve_addons/edi_purchase_base/models/supplier_price_list.py
> +                                                 'product_tmpl_id': product_tmpl_id.id})
Same here, code-style

2020-04-22 10:40 UTC, ivantodorovich commented
I'm mergin this PR here, code-style is not blocking for 9.0.

Can you forward-port to 12.0 in https://github.com/druidoo/foodcoops ?
(code-style is important there)

2020-04-22 10:40 UTC, merged

2020-04-24 05:33 UTC, siddharth7815 commented
> I'm mergin this PR here, code-style is not blocking for 9.0.
> 
> Can you forward-port to 12.0 in https://github.com/druidoo/foodcoops ?
> (code-style is important there)

Please have a look Pr for this:  https://github.com/druidoo/FoodCoops/pull/142